### ISSUE TITLE
Remove links from SolrDocument thumbnails if they are private

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#1006]
(i.e. just show the image but don't make it clickable to the full record)

**Comment by jkeck** [comment]
Just verified this.  It looks like we will not display the image for private documents.

Should we continue that behavior @ggeisler (and therefore just close this ticket) or should we change that to allow private document's thumbnails to be individually selected in widgets and simply remove the link? (I'm in favor of the "Do Nothing"™ approach).

**Comment by ggeisler** [comment]
Sure, the "Do Nothing"™ approach is fine. That's what I thought we were doing before this came up.

I think we'll need a solution for displaying non-repo images (intended by the curator to be used as supplementary images, not items that have an Item Record page) in widgets, but we can address that separately.

**Comment by jkeck** [comment]
:+1:
