### ISSUE TITLE
Update GitHub readme - install process

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1026]

**Comment by cbeer** [comment]
What more are you thinking about? I think the install section in the readme is technically correct (the best kind..) without getting into the fuzzy world of configuration options.

**Comment by ggeisler** [comment]
I didn't have anything specific in mind when creating the ticket; this was just transcribed from the documentation list on the whiteboard after our Monday meeting. If you and @jkeck think we've already covered installation sufficiently feel free to close the ticket.

**Comment by ggeisler** [comment]
Unless @snydman had something specific in mind, based on conversations with other potential adopters.

**Comment by jkeck** [comment]
I just want to make sure we validate that the installation process is smooth and documented before we shift focus to other things.  Perhaps we can get somebody in DLSS not yet familiar with Blacklight to go through the install process next week and verify that it all makes sense and they get what they expect.

**Comment by jkeck** [comment]
I think something along the lines of, although maybe not as heavy-handed as, Sufia's [Prerequisites](https://github.com/projecthydra/sufia#prerequisites) and [Rails](https://github.com/projecthydra/sufia#rails) sections would probably be a good start.

I think we've heard that people expected a solr instance after running the template installer.  While I know that we intentionally do not provide solr for them, I think having a note somewhere along the way explaining that they need to set that up themselves.  We could either give links to the appropriate info, or we could provide the rake tasks they could run to get solr installed and configured appropriately for Spotlight.

**Comment by cbeer** [comment]
Thanks, those sufia examples are nice.

**Comment by cbeer** [comment]
I've updated the README, but we need to make some decisions (#1065 + #1066) about what state the template installer leaves you in. I'm also tempted to drop the "install it the hard way" documentation entirely. Anyone that it is useful to can a) figure out the install steps themselves (because it follows conventions), or b) look in the template generator and do the same thing.
