### ISSUE TITLE
Don't use browse category-specific masthead for edit pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1038]
If the curator has selected a masthead for a browse category, we show that both for the browse category detail page _and_ on the admin side on the edit page for that browse category (as in screenshot below). We don't want to do the latter; the Edit Browse Category page should just show the normal site masthead.

![curation_-_curation_-_browse___bob_fitch_photography_archive_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6587712/2ddd17e0-c745-11e4-9b44-239d152704ea.png)

**Comment by jkeck** [comment]
We should check for the action param.
