### ISSUE TITLE
Something wrong with non-repository items square indexing?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1103]
In a brand new spotlight exhibit (that's going to be impossible to debug again..), I uploaded an image (http://stanislausriver.org/files/original/49a8aed196c506c3e97f7138e13b6e87.jpg) but a square thumbnail wasn't made / wasn't indexed correctly, and so it isn't showing up on the `catalog#admin` page. The image shows up fine on the `catalog#show` page, though.

**Comment by jkeck** [comment]
@cbeer I think this is just because we're not generating a configured thumbnail field into the application.  AFAICT the version is being created and indexed, but since we never tell `blacklight-gallery` which field to get the thumb from we don't get anything in the UI.
