### ISSUE TITLE
limit size of image used for slideshow and masthead cropping

### ISSUE THREAD

**Issue by snydman** [sul-dlss/spotlight#1146]
Following the ongoing discussions about performance issues when very large images are displayed in a slideshow view or used to produced cropped mastheads. 

Short of full IIIF support, can we take the intermediate step of limiting the size of images used in slideshow view or for cropping?  

I am not sure what the right size is, but this is something that can be adjusted for local contstraints. An image must be large enough support full-screen slideshow mode or to crop a zoomed-in portion of an image for a masthead.  But must not be so big that it creates a user experience issue or prohibits the cropping function altogether. 

Something like https://stacks.stanford.edu/image/iiif/fw686gh2768%252FAM_0117/full/!3000,3000/0/default.jpg

?

**Comment by ggeisler** [comment]
I think 2000px on the long edge might be large enough for any normal, expected use today (viewing on up to a 27" or 30" display). If the value is configurable that could be adjusted for special/future implementations.

Would it work like this (I think maybe @jkeck suggested something like this before?)?

* When items are added to an exhibit, a derivative is made, at 2000px on long side 
* This derivative is indexed as the "full-sized display image" (or the source image is indexed as that if less than 2000px) for the item
* When the curator needs to do a crop, the "full-sized display image" is used as the source image
* When a slideshow is displayed, the "full-sized display image" is used as the source image

If we could do this, I think it would be a big UX improvement, both for the curator making crops in an exhibit with large full images (e.g., MofA) and for the end-user (e.g., quicker page loading for slideshow with images that use entire available viewport).

I suppose there could be some edge cases where this strategy would foil the curator who wants a certain detailed crop that would require a full 5000px image, but I'm guessing that would be very rare, and they could get around the problem by uploading the large image and cropping from that.

**Comment by cbeer** [comment]
Replaces by #1184
