### ISSUE TITLE
Document persistence behavior and cooperation with other applications to avoid clobbering each others Solr updates

### ISSUE THREAD

**Issue by escowles** [sul-dlss/spotlight#1152]
In https://github.com/projecthydra/active_fedora/issues/778, a proposal was made to update the Solr configuration to use only stored fields by default to enable atomic Solr updates.  Spotlight was one of the use cases mentioned for this, so it would be good to know how Spotlight updates the Solr index, if Spotlight can be used without atomic updates (and what the impact of disabling them would be), and how other applications updating the Solr index interact with Spotlight to avoid data loss.

#316 and #315 seem relevant, but look like the are only proposals.

**Comment by cbeer** [comment]
Indeed, they are only proposals. Ideally, someone who actually wants those features will champion them.

The basic model is an application should mixin an indexing strategy to their `SolrDocument` that provides a `#reindex` method, e.g. https://github.com/sul-dlss/spotlight/blob/master/app/models/concerns/spotlight/solr_document/atomic_updates.rb#L6-10

We've also provided a couple basic endpoints that may be good starting points, including:

 - a shim that behaves like Solr (for some definition of "like Solr"): https://github.com/sul-dlss/spotlight/blob/master/app/controllers/spotlight/solr_controller.rb

- an endpoint to retrieve Spotlight's exhibit-specific data for a document: https://github.com/sul-dlss/spotlight/blob/master/app/controllers/spotlight/catalog_controller.rb#L219-222 (E.g. `/catalog/:id.solr_json`)

**Comment by escowles** [comment]
Thanks for the pointers -- these do indeed look like good starting points for implementing alternate indexing strategies.  It looks like it would be pretty straightforward to implement a custom indexing approach if you weren't able to use atomic updates.

I think this would be really helpful to anyone who wanted to do this, so I'd encourage you to add it to the wiki.
