### ISSUE TITLE
Add exhibit-specific fields to Search Facets list

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1153]
A curator wants to use an exhibit-specific field as the basis for multiple browse categories (one per value of that field). Currently we don't show exhibit-specific fields as potential facets so creating the saved search for the browse category can be difficult. If the curator could create an exhibit-specific field and then select it to show as a facet, the curator could create the saved searches easier.

The curator can use tags to accomplish the same thing, but in some cases using an exhibit-specific field makes more sense than having to create tags to produce the desired search result.

**Comment by cbeer** [comment]
I thought we were doing this with the custom field type free text vs controlled vocabulary?

**Comment by ggeisler** [comment]
:+1: You are correct!
