### ISSUE TITLE
Add Admin UI for configuring search fields

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1174]
Assume we will enable the admin to:

- Turn on/off the fielded search option
- Configure the fields shown in the fielded search select

**Comment by cbeer** [comment]
Spotlight serialized and deserializes the Blacklight configuration in the [`Spotlight::BlacklightConfiguration`](https://github.com/sul-dlss/spotlight/blob/master/app/models/spotlight/blacklight_configuration.rb) model. 

We have controllers for the different types of config, e.g.:

- https://github.com/sul-dlss/spotlight/blob/master/app/controllers/spotlight/metadata_configurations_controller.rb
- https://github.com/sul-dlss/spotlight/blob/master/app/controllers/spotlight/facet_configurations_controller.rb
- https://github.com/sul-dlss/spotlight/blob/master/app/controllers/spotlight/sort_configurations_controller.rb

Under the guise of this ticket, we might consider if there are common components to those controllers that may be appropriate to pull up to a `Spotlight::BlacklightConfigurationsController` superclass.

**Comment by cbeer** [comment]
@ggeisler to provide a design document for reorganizing the search configuration.

**Comment by ggeisler** [comment]
The mockups below encompass two related updates from the UI point of view:

* Moving several existing search-related configuration options to a single, tabbed page
* Adding a new fielded search configuration to that tabbed page

With these changes, the Curation sidebar should no longer include the "Search facets" or "Sort fields" menu items. In their their place there should be a single menu item called "Search."

There are three tabs on the new Curation > "Search" page. 

## Options

- Includes the existing "searchable" checkbox from the Admin > Appearance page, Exhibit style tab
- Includes the new configuration for field-based search.
- Note that the field-based search configuration determines whether to enable the fielded search dropdown menu on the site searchbox (which exists in Blacklight, but is not current exposed in Spotlight)

![1-options](https://cloud.githubusercontent.com/assets/101482/10436500/a7e1e364-70db-11e5-96f4-9dc4a4ed7db0.png)

## Facets

- Moved from the Curation > Search facets page but should work the same
- Text above the facet configuration is new

![2-facets](https://cloud.githubusercontent.com/assets/101482/10436578/18964a1e-70dc-11e5-83eb-740e862046c9.png)

## Results

- Result page types and Default results per page are moved from the Admin > Appearance page
- Sort fields are moved from the Curation > Sort fields page

![3-results](https://cloud.githubusercontent.com/assets/101482/10436614/551c6810-70dc-11e5-86bf-4ead26df8481.png)
