### ISSUE TITLE
Update default home page text

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1187]
The default homepage text block includes a link to "Curation > Search facets." However, as part of #1174  the Curation sidebar links will no longer include a link to "Search facets." They will include a link to "Search." 

To reflect that update, when #1174 is completed step 4 of the default home page text block should be updated. The text "Curation > Search facets" should be changed to "Curation > Search" and the link for that text should be updated to the new path for the Curation > Search page.

![the_edward_a__feigenbaum_papers_-_stanford_university_libraries](https://cloud.githubusercontent.com/assets/101482/10462176/16192eda-7192-11e5-8a53-c0d9fc63d42d.png)

**Comment by ndushay** [comment]
connected to #1174
