### ISSUE TITLE
Create Item Row widget for non-exhibit items

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1196]
A potentially common use case is that a curator wants to show an image (maybe more than one) with some text next to it -- as the current Item Row widget does -- but the image to show is not an image associated with an item in the repository or one that should be a first-class object in the exhibit (i.e., it doesn't need a show page with metadata fields, etc.).

Example from a non-Spotlight exhibit a curator is trying to replicate in Spotlight (image is just a book cover for a book we don't own):

![digital_exhibit___sul](https://cloud.githubusercontent.com/assets/101482/10524738/f9e8a876-7335-11e5-89ad-d3b34bc81ceb.png)

I suggest we make a version of the existing Item Row widget that is basically the same, except that instead of the repeatable autocomplete field used to select an item, we show a repeatable image upload button. (I can do a mockup if necessary, but will assume the idea is clear.)

On the display side it would work almost identically to the existing Item Row widget, except the images shouldn't be linked to anything.

**Comment by ggeisler** [comment]
Some other details for the widget:

Name: Uploaded Item Row

Description text: This widget displays uploaded items in a horizontal row. Optionally, you can add a heading and/or text to be displayed adjacent to the items.

Add as last item under the "Standard Widgets" section of the widget selection panel, with same icon as the exhibit item row widget

**Comment by jkeck** [comment]
Closed by #1245
