### ISSUE TITLE
use released gems

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/spotlight#1204]
stop using unreleased code from github branches whenever possible.  Document why when not possible.

 - [ ] harvestdor
 - [ ] harvestdor-indexer
 - [ ] gdor-indexer
...

**Comment by cbeer** [comment]
Does:

- https://github.com/sul-dlss/sul-exhibits-template/pull/64
- https://github.com/sul-dlss/spotlight-dor-resources/pull/19

resolve this ticket?

**Comment by ndushay** [comment]
I think so ...

**Comment by ndushay** [comment]
I believe this is done.
