### ISSUE TITLE
Evaluate OCR quality for other potential spotlight collections

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1227]
@snydman suggests:

- Gould
- Jarndyce
- ME310
- Homebrew Computing
- GATT

in addition to Feigenbaum

If we need to, we can spin up a new exhibit to try it out.

**Comment by ndushay** [comment]
Homebrew Computing
* example items:  ```rq244mg8348```, ```rm399dh9965```
* full text  is part of PDF;  searching for text within Acrobat Reader results in correct highlighting
* content metadata
![homebrew content metadata](https://cloud.githubusercontent.com/assets/96775/11256735/8d947c12-8e02-11e5-941c-863512d9e166.png)

**Comment by cbeer** [comment]
But not any text files, huh? So we'd have to figure out how to do full text extraction first.

**Comment by snydman** [comment]
Please check with Tony Calavano. I would be surprised if there were not txt/alto type files for Homebrew and these other collections if produced by our in-house OCR workflow.  Whether or not it is accessioned or referenced in ContentMD is a different question, but should be.

**Comment by ndushay** [comment]
Peter already told me he used a ruby gem to extract text from pdf for Feigenbaum:
![extract text](https://cloud.githubusercontent.com/assets/96775/11257323/b1e8e71c-8e05-11e5-9473-b02e3b6980a4.png)

"i was surprised how fast and generally error free it was, i think it did all 16k pdfs in a couple hours;  of course, it was not doing ocr, just pulling text out and saving .txt files"

**Comment by ndushay** [comment]
Also, I think Solr can index a PDF file, per https://wiki.apache.org/solr/ExtractingRequestHandler.   I'm not sure how we would go about incorporating this into our workflow ...

**Comment by ndushay** [comment]
ME310

* example items:  ```wz402qb2020```, ```wc053rq8118```
* only PDF files in argo (and published)
* PDF files have full-text as they are searchable
  * (https://stacks.stanford.edu/file/druid:wz402qb2020/Merck-Fall-ME 310 Doc.pdf)

**Comment by ndushay** [comment]
Gould

* example items:  ```bq009nf1733 ```, ```bb260cm8880```, ```cd722rj9672```
* these items have only jp2 and jpeg files for pages, per argo

**Comment by ndushay** [comment]
Feigenbaum

* example items:  ```sd411gd2140```, ```bb210ft8492```, ```bb224bb5445```
* looks like there is alto xml files for individual pages
* Peter used docsplit to get text out of pdf files - this is the full text being indexed in Feigenbaum spotlight exhibit (and quality of OCR is bad)
* @calavano is text in alto xml from individual pages diff from text in pdf for full doc?  (see also separate email soon to be sent.)

**Comment by ndushay** [comment]
Jarndyce

* example items:  ```bb846gv7194```, ```bc647th4106```
* pdf for entire book is searchable, and individual pages also
* individual pages have alto xml files

**Comment by ndushay** [comment]
GATT  (59K docs!)

* example items:  ```bb023ts9016```, ```bb051yp1914```, ```bb031kf1028```
* .txt files for some individual pages  <-- how did we get this?  Quick eyeballing it looks pretty good
* TEI for bb023ts9016, bb031kf1028

**Comment by ndushay** [comment]
![email to tony](https://cloud.githubusercontent.com/assets/96775/11259201/94a69226-8e14-11e5-9843-717b7992c023.png)

**Comment by snydman** [comment]
@ndushay About GATT. These files were scanned from microfiche, and OCR and TEI creation was outsourced to a vendor.  They had an OCR accuracy threshold in the contract, so the OCR should be pretty good.  It was a long time ago, but I believe we required them to deliver to us PDF, TEI and TXT in addition to TIF image files.  All of that text comes from the lightly corrected (but still imperfect) OCR.

**Comment by snydman** [comment]
@ndushay seems like Jarndyce and Homebrew (and maybe GATT) would be good examples beyond feigenbaum to test against. Jarndyce and Homebrew for certain represent the current text output routinely produced by our labs (using ABBYY).

**Comment by ndushay** [comment]
![email from tony](https://cloud.githubusercontent.com/assets/96775/11282263/3b3a3608-8eb3-11e5-95b4-f3ec29cd3736.png)

**Comment by ndushay** [comment]
![more tony email](https://cloud.githubusercontent.com/assets/96775/11283062/9c664dfa-8eb7-11e5-8e41-5d75c418e5e1.png)

**Comment by ndushay** [comment]
should we close this ticket?  It has the info whether it is closed or open, and we did discuss it.  We concluded that existing collections with decent quality English full text are:

- Jarndyce
- Homebrew
- GATT  (but from TEI)

And that for the future, we should determine how to accession full text from Abbyy to facilitate indexing (or how to adjust indexing to take the full-text from page level and document level pdfs)
