### ISSUE TITLE
Dig up Hathitrust documentation about page-level full-text indexing

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1228]
I know I've seen something before (presentation? blog post? paper?) about HathiTrust's approach to page-level full text indexing. I think it involved multiple solr indexes and on-the-fly indexing.

We should find that documentation, and possibly follow up with them to find out if that's still their preferred approach.

**Comment by ndushay** [comment]
https://www.hathitrust.org/blogs/large-scale-search/tale-two-solrs-0    explains that they have document level full text, and then an "on demand" page level solr index for page level results.

**Comment by ndushay** [comment]
https://www.hathitrust.org/full-text-search-features-and-analysis   this is interesting as the "show snippets" isn't at the top of the list

**Comment by ndushay** [comment]
page level full text results -  NOT snippets:

![hathi page level view](https://cloud.githubusercontent.com/assets/96775/11253355/d263871a-8def-11e5-8fec-0761e68f9636.png)

**Comment by ndushay** [comment]
@cbeer not sure where else we are going with this right now?

**Comment by cbeer** [comment]
This looks great. Let's use this to inform our discussion with @snydman at the next sprint planning.
