### ISSUE TITLE
Move exhibit analytics to a new page

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1236]
The exhibits analytics on the curator dashboard are blocking requests to the Google Analytics API. Instead of rendering them inline on that page, we should move that to a new page entirely.

**Comment by ggeisler** [comment]
Related to #589

**Comment by ggeisler** [comment]
I suggest we create a new sidebar link in the admin called "Analytics." This gives us a dedicated page for showing the exhibit site's analytics. This ticket should just add the new sidebar link and make that resolve to an Analytics page. Another ticket (#1271) can address adding additional metrics to that page.

### Sidebar link

![sidebar-link-location](https://cloud.githubusercontent.com/assets/101482/11384478/f7e3b0c6-92c4-11e5-9ec4-4a00a7c9dfbe.png)

### New page

Move rendering of the `dashboards/_analytics.html.erb` partial to a new page that looks like this:

![curation_-_dashboard___maps_of_africa__an_online_exhibit_-_stanford_university_libraries](https://cloud.githubusercontent.com/assets/101482/11384535/72633f1a-92c5-11e5-8a1e-05ec43287ec9.png)
