### ISSUE TITLE
[PROPOSAL] Disable scss-lint rule about underscore vs hyphen

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1247]
Spotlight has many false-positives from this rule, where we're styling attributes from other gems or libraries. Should we try to disable this rule?

**Comment by ggeisler** [comment]
:+1: Perhaps most of us know to use hyphens rather than underscores in CSS when possible, so not getting the reminder shouldn't open the door to inconsistencies too often? And maybe we can trust pull request reviews to catch the occasions when an underscore is used unnecessarily.

**Comment by jkeck** [comment]
:+1:

**Comment by ndushay** [comment]
:+1:

**Comment by peetucket** [comment]
:thumbsup:
