### ISSUE TITLE
Consider advertising factories in a railtie

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#1270]
See the [PR in FactoryGirlRails](https://github.com/thoughtbot/factory_girl_rails/pull/42)

I *think* we just need to add something along the lines of

```ruby
initializer 'spotlight.factories', after: 'factory_girl.set_factory_paths' do
  FactoryGirl.definition_file_paths << File.expand_path('../../../spec/factories', __FILE__) if defined?(FactoryGirl)
end
```

in `config/engine.rb` and then apps (and gems I believe) that require Spotlight will have access to the Spotlight defined factories in their tests.

**Comment by cbeer** [comment]
:+1:

**Comment by cbeer** [comment]
It works like a charm. The only downside, and we can figure it out later, is that `factory_girl` doesn't like you to define multiple factories with the same name. If it turns out to be a big deal, we should figure out how to namespace the spotlight-provided factories a little better.

**Comment by jkeck** [comment]
Yeah, I was worried about that.  We could easily rename all our factories to include `spotlight_` or something like that.
