### ISSUE TITLE
Update the text label for "All fields" in fielded search drop-down to "Everything"

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight#1282]
This clarifies that the default is to search everything, including full text if available.

**Comment by peetucket** [comment]
update spotlight, then update sul_exhibits_template to use latest spotlight gem

**Comment by peetucket** [comment]
spotlight updated, once new gem is cut, we can update sul_exhibits_template to use latest

**Comment by cbeer** [comment]
And update the configuration in the app: https://github.com/sul-dlss/sul_exhibits_template/blob/master/app/controllers/catalog_controller.rb#L159

**Comment by ndushay** [comment]
Is this code in spotlight 0.9?  if so, sul_exhibits_template is ready for its tweak.

**Comment by peetucket** [comment]
Spotlight has it in master, not sure if a new release has been cut yet.

**Comment by cbeer** [comment]
In any case, updating spotlight is orthogonal to updating sul_exhibits_template. This is just default application configuration, not any sort of logic change in spotlight.

**Comment by peetucket** [comment]
ok, so i'll submit the PR for this change to sul_exihibits_template then #123
