### ISSUE TITLE
Set the default sort order per facet

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight#1283]
Admins should be able to set the default sort order of a facet (e.g. "Year" should be sortable by A-Z/number instead of frequency of value occurrence).

**Comment by ggeisler** [comment]
I suggest we add an "Options" link to the right-side of the facet panels, where the link expands and collapses an additional row in the panel to hold the facet value sort order. (I'll post another comment with a simpler alternative, but the expand/collapse approach reduces visual clutter I think is undesirable in the alternative.)

I don't think we need to add new text to the instructions (should be self-explantory? plus I'd really like to remove the instructions entirely, but would like to do some user testing first).

### Default view of facet panels

A additional row with the sort field label and control is added to each facet panel, but hidden by default. The "Options" link and icon is added to the right-side of each existing panel row.

![option - a](https://cloud.githubusercontent.com/assets/101482/11574364/2218c4f6-99c0-11e5-829b-846aefafbdd2.png)

### Facet panel options expanded

When the "Options" link is selected, the panel is expanded to display the additional panel row containing the sort field options:

![option - b](https://cloud.githubusercontent.com/assets/101482/11574367/2b632722-99c0-11e5-8a0e-76310307a1f1.png)

### Facet sort order options

Frequency should be the default (as it is now). I don't see a real need to sort by frequency ascending (though obviously we could add that if someone thinks a curator could realistically want to do it). Sorting by value ascending or descending would handle the other potential options, I think?

![option - c](https://cloud.githubusercontent.com/assets/101482/11574373/3150103c-99c0-11e5-9f53-e628d4751b22.png)

Changes to the panel sort order are saved only when the admin selects **Save changes**, as with the other changes to the page.

Obviously, the other part of this work is to actually save the sort preference for each facet to the database and to reference that saved setting when displaying the facets on the home and result pages.

**Comment by ggeisler** [comment]
Just for the record, below is an alternative to the expand/collapse options approach above. I think this would be a bit easier to implement, but I worry about the visual clutter and more need to deal with responsive sizing to present everything cleanly. I think the previous approach would be better.

This approach would simply add the sort field label and options to the existing panel rows.

![option 1a - md](https://cloud.githubusercontent.com/assets/101482/11575675/36107876-99c7-11e5-9c6d-7658159e0c94.png)

**Comment by cbeer** [comment]
:+1: . I think the first option shouldn't be too hard. 

I don't think we can do value z-a easily (it'd probably take another solr field with some crazy reverse sorting applied..).

**Comment by ggeisler** [comment]
Okay, though if we can't sort descending (I thought this might be useful for showing most recent dates first) and have only two options to choose from, perhaps we should go with radio buttons?

![radio buttons](https://cloud.githubusercontent.com/assets/101482/11576326/ab711adc-99ca-11e5-9f34-4c0f69f3cd3a.png)

**Comment by cbeer** [comment]
:+1:
