### ISSUE TITLE
Add fallback image for case where exhibit doesn't have thumbnail image defined

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1389]
On the exhibits home page, the exhibit title and the "Unpublished" label elements look out of place when an exhibit has no thumbnail image. To ensure the image element is there (which ensures the title and label elements will be positioned correctly) use a fallback image when no exhibit thumbnail exists.

### No image exists
![blacklight 2](https://cloud.githubusercontent.com/assets/101482/11886721/27d9cbba-a4e2-11e5-97bd-f56f720ff8b3.png)

--
### Fallback image used
![blacklight](https://cloud.githubusercontent.com/assets/101482/11886727/394c726c-a4e2-11e5-8d14-93cc7d87f4f4.png)

### Fallback image file

![exhibit-thumbnail-fallback](https://cloud.githubusercontent.com/assets/101482/11886742/591d8b44-a4e2-11e5-9359-7f1182c1271c.jpg)

**Comment by cbeer** [comment]
We should be able to use 

https://github.com/carrierwaveuploader/carrierwave#providing-a-default-url

to make this work.
