### ISSUE TITLE
Problem with exhibit features page in v0.17.0

### ISSUE THREAD

**Issue by ronan-mch** [sul-dlss/spotlight#1436]
After upgrading to `v0.17.0` I was unable to access the Curation Feature Page from the admin interface ( `spotlight/<exhibit>/feature` ). CanCan returned an error on `load_resource`. Downgrading resolved the issue.

**Comment by cbeer** [comment]
I'm not able to reproduce this myself. Can you share the stack trace?

**Comment by ronan-mch** [comment]
Apologies Chris, it seems to be working for me again. My best guess is that there was something screwy with my environment which I didn't notice.
