### ISSUE TITLE
Remove count labels from Admin sections

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1440]
On some admin pages we have these little labels with counts of the relevant item, such as on the Tags page:

![curation_-_tags_3___maps_of_africa__an_online_exhibit_-_online_exhibits](https://cloud.githubusercontent.com/assets/101482/13154589/898b7eee-d62e-11e5-89c3-7d5033aa0b18.png)

We only show these on a couple of pages (Tags, Browse categories, not sure if anywhere else). Although these were in my original designs for Spotlight I don't think they've ended up having any real value to the user, and the fact that they are only shown on a small subset of admin pages feels odd. 

Any objection to me removing these?

**Comment by ggeisler** [comment]
(We could of course hide them in our SUL exhibits, but I'm suggesting they probably don't have value for any Spotlight implementor.)

**Comment by cbeer** [comment]
:+1:
