### ISSUE TITLE
Create icons for search results and other new widgets

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#610]
![st-widgets](https://cloud.githubusercontent.com/assets/96776/2621374/c3ca2016-bc53-11e3-9ad5-adf6de6b6634.png)

**Comment by ggeisler** [comment]
- [ ] Text
- [ ] Horizontal rule
- [ ] Browse categories
- [ ] Feature pages
- [ ] Search results
- [ ] Item row
- [ ] Item carousel
- [ ] Item slideshow
- [ ] Item grid
