### ISSUE TITLE
Image widget not working when application is mounted under a suburi

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#672]
The Sir Trevor image widget isn't working on the ```exhibits``` or ```exhibits-demo``` servers. It works locally, so this might be a server-side gem configuration issue?

Giving the widget an image results in a "There is a problem with your upload" message from the widget and no image is displayed on the saved page.

(This might be more appropriate as a ticket in the sul-exhibits-template repo, but @snydman suggested we add it to our current sprint so that it gets attention immediately. This is an important fix for preparing our demo site for OR.)

**Comment by cbeer** [comment]
Confirmed still a problem.
