### ISSUE TITLE
Slideshow show images should fit viewport if larger image source available

### ISSUE THREAD

**Issue by snydman** [sul-dlss/spotlight#695]
The slideshow view does not appear to have a mechanism to use a larger image source if available.  The image in the slideshow view should fill the slideshow viewport if possible. 

For Stanford exhibits, our images are hosted at IIIF image service which could allow us to use a larger image in SlideShow view.  Is this possible? Will this need to be a local Stanford customization?

![image](https://cloud.githubusercontent.com/assets/3279382/3176705/19d6bf6c-ec08-11e3-867a-d0805aa3f4c5.png)

**Comment by jkeck** [comment]
Do this w/ the carousel too.

**Comment by cbeer** [comment]
Fixed in #1011
