### ISSUE TITLE
Menu bar could be more intuitive

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#718]
It took me a little while to remember how to use Spotlight. At the very least, I think the dashboard link and the create exhibit link need to be grouped together, but maybe the exhibit-building features need to be separated from the user features?

![screen shot 2014-11-12 at 9 00 02 am](https://cloud.githubusercontent.com/assets/111218/5014408/548c5264-6a4a-11e4-8c0a-f2fe64363f70.png)

**Comment by ggeisler** [comment]
For now, how about a simple rearrangement, moving the Change Password link to be grouped with Sign out:

![with-create-exhibit](https://cloud.githubusercontent.com/assets/101482/6469347/7e405130-c190-11e4-919f-4ac178639366.png)

Eventually there could be a middle section with Help and possibly other documentation links.

Ideally, we should also rename the Create Exhibit and Change Password links to only use an initial capital letter, as shown in the screenshot (the SUL style is sentence case for headings etc., although we don't apply that consistently).
