### ISSUE TITLE
Should sort and per-page widgets appear in widget embed?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#826]

**Comment by ggeisler** [comment]
@cbeer Are you asking whether the sort and per-page select dropdowns should be part of the search results widget as it is displayed to the end-user?

**Comment by cbeer** [comment]
Sure, let's go with that. I forget the context here.

**Comment by ggeisler** [comment]
Well, I've been thinking myself that the page would look better without the sort and per-page dropdowns so I'm happy to go with that. 

One issue is that if the curator selects to include more than one result view in the widget, there's still a need for the view icons so we don't save any vertical space. But it reduces visual clutter and if the curator does select only one view it will reduce vertical space and look cleaner on the page.
