### ISSUE TITLE
Couldn't find Spotlight::Exhibit with 'id'=default-exhibit

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#836]
I followed the install instruction https://github.com/sul-dlss/spotlight
but http://localhost:3000/spotlight/default-exhibit reported Couldn't find Spotlight::Exhibit with 'id'=default-exhibit

**Comment by whisere** [comment]
followed the "To set up your development environment"

**Comment by jkeck** [comment]
@whisere did you get this error by going directly to `http://localhost:3000/spotlight/default-exhibit` after install or did you go to `http://localhost:3000` and then receive the error?

**Comment by whisere** [comment]
Thanks, after install I go to http://localhost:3000 and got directed to http://localhost:3000/spotlight/default-exhibit, and received the error

**Comment by jkeck** [comment]
@whisere which version of rails are you using?  We're currently having some issues w/ the rails 4.2 release and trying to merge in some code to deal w/ the latest version.  I wonder if this is related.

**Comment by whisere** [comment]
I am using ruby-2.1.5@rails4.1 would that be a problem? which one I should use?

**Comment by whisere** [comment]
here is some error in the development log:
Processing by Spotlight::HomePagesController#show as HTML
  Parameters: {"exhibit_id"=>"default-exhibit"}
  [1m[35mSpotlight::Exhibit Load (0.1ms)[0m  SELECT  "spotlight_exhibits".* FROM "spotlight_exhibits" WHERE "spotlight_exhibits"."id" = ? LIMIT 1  [["id", 0]]
Completed 404 Not Found in 4ms

ActiveRecord::RecordNotFound (Couldn't find Spotlight::Exhibit with 'id'=default-exhibit):

**Comment by jkeck** [comment]
Hmm, this seems like an issue we have seen when running under rails 4.2.  Maybe you can help us validate that. 

Give this a  try to get spotlight installed.
* Check out the [rails42 branch](https://github.com/sul-dlss/spotlight/tree/rails42).
* Remove the Gemfile.lock in the spotlight root.
* Remove the spec/internal directory.
* Follow the normal development environment instructions (including a fresh bundle install).

Report back here if you're still having issues.

We're looking into getting that branch merged into master (most likely tomorrow) but you can try it out now to see if it can get you moving forward before then.

**Comment by whisere** [comment]
Thanks When I run this step
rake engine_cart:generate
it reported
rake aborted!
Errno::ENOENT: No such file or directory @ sys_fail2 - (/tmp/d20150107-3940-1yaxcx4/internal, ./spec/internal)
/home/username/.rvm/gems/ruby-2.1.5@rails4.1/gems/engine_cart-0.4.0/lib/engine_cart/tasks/engine_cart.rake:41:in `block (3 levels) in <top (required)>'
/home/username/.rvm/gems/ruby-2.1.5@rails4.1/gems/engine_cart-0.4.0/lib/engine_cart/tasks/engine_cart.rake:26:in `block (2 levels) in <top (required)>'
/home/username/.rvm/gems/ruby-2.1.5@rails4.1/gems/engine_cart-0.4.0/lib/engine_cart/tasks/engine_cart.rake:62:in `block (2 levels) in <top (required)>'
/home/username/.rvm/gems/ruby-2.1.5@rails4.1/bin/ruby_executable_hooks:15:in `eval'
/home/username/.rvm/gems/ruby-2.1.5@rails4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => engine_cart:create_test_rails_app
(See full trace by running task with --trace)

**Comment by whisere** [comment]
I cloned rails42 branch:
git clone -b rails42 https://github.com/sul-dlss/spotlight.git
instead of downloading the zip file https://github.com/sul-dlss/spotlight/archive/rails42.zip
It seems working fine now! Thanks!

**Comment by jkeck** [comment]
Thanks for reporting back @whisere.
