### ISSUE TITLE
How do we handle viewing non-repository images on the full record view

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#838]
We currently attempt to load an OSD instance using indexed IIIF info.

**Comment by ggeisler** [comment]
Putting the non-repo image in an OSD viewer would be ideal. Basically, handling it as similar as possible to a repo item.

**Comment by cbeer** [comment]
(I'd note that in our exhibits, we're using sul-embed for displaying items, not OSD out of the box.)

**Comment by jkeck** [comment]
We can use the [Legacy Image Pyramid](https://openseadragon.github.io/examples/tilesource-legacy/) to load a static image through an OSD instance. ([example](https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/javascripts/jquery.stackmap.js#L68-L74))

However, AFAICT the `OpenSeadragon` gem only allows for a tilesource at a URL and can't be passed directly as an object as in the above example.
