### ISSUE TITLE
Do we need form-field help for non-repository image upload?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#840]
We're limiting the image formats (just jpg and png I think?), should we put any form-field help indicating which formats we're allowing the user to upload?

**Comment by ggeisler** [comment]
Good idea. How about something like this:

![css_ _bootstrap](https://cloud.githubusercontent.com/assets/101482/5668867/b1b75e8e-9727-11e4-9da2-96eab0cd789d.png)

````html
<p class="help-block">Must be either a .jpg or .png file</p>

**Comment by cbeer** [comment]
Is there any way we can introspect carrierwave and see what's actually supported?

**Comment by jkeck** [comment]
Yes, we limit file extensions in carrierwave by adding an `extension_white_list` method on our uploader class that we can read from.

**Comment by ggeisler** [comment]
Based on discussion with @jkeck let's change the help text to something like:

> Valid file types: .jpg, .png

Where the actual file type extensions are populated from the `extension_white_list` or equivalent configuration method used to set the `extension_white_list` values.
