### ISSUE TITLE
Should items be deletable from an exhibit?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#843]
@jkeck asked this question in #841 for non-repository items, but it could also apply to repository items?

Is it sufficient for a curator to just uncheck an item from Public view, or should they be deletable from the exhibit entirely?

If we do want to allow an item to be deleted from an exhibit, where in the UI is this done (from the Item Record page or the Curation > Items list)?

**Comment by cbeer** [comment]
I'd worry about what deleting an item means, especially if it was imported into an exhibit as part of collection. Would we have to keep track of it, so whenever we reindex we're sure to delete it again? Sounds messy.

**Comment by ggeisler** [comment]
And you'd have to reindex as soon as an item is deleted, or else it could show up in facets/autocomplete?

**Comment by cbeer** [comment]
No, my concern is:

- the curator selects a collection for an exhibit
- deletes a single item from the exhibit
- metadata remediation, act of god, etc happens and we want to rebuild the whole index.. so we grab the collection and all its members and reindex them
- unless we track what items were deleted and somehow reference that list on indexing, the deleted item would reappear.

**Comment by ggeisler** [comment]
Yep, I understand. I just thought there might be an additional problem with needing to reindex after every delete to prevent the user from being presented with links to items the curator removed. In any case, your concern seems significant enough to me to suggest we not worry about enabling deleting items, and just let the curator hide items they don't want to be accessible any longer. If this strategy isn't sufficient I'm sure we'll hear about it over time.
