### ISSUE TITLE
Default homepage should include some curator-friendly content

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#85]
Since every exhibit will come with an existing homepage, we should include some sample content on the default homepage that gives the curator a good idea of what is possible in terms of customizing the page for his or her exhibit.

Some mix of widgets and explanatory text (using the text widget).

**Comment by ggeisler** [comment]
If possible, let's replace the current text used on the homepage of a newly-generated site:

![current-text](https://cloud.githubusercontent.com/assets/101482/6714629/9fa0e7be-cd56-11e4-903f-a4efa17c0976.png)

With something like this:

![proposed-text](https://cloud.githubusercontent.com/assets/101482/6714640/afbb6fa2-cd56-11e4-9c2d-f32590cf3110.png)

Here's the markdown code:

````md
## Welcome to your new exhibit!

When you're ready to begin building your exhibit, here's how to get started:

1. Visit the [Administrative Dashboard Settings](edit) page to configure the exhibit title and subtitle.

2. Next, go to the [Administration > Appearance](appearance/edit) page to add a site masthead image and configure other appearance options.

3. If you want help building the exhibit, use the [Administration > Users](users) page to add other user accounts.

4. Use the Curation pages, such as [Curation > Metadata](edit/metadata) and [Curation > Search Facets](edit/facets), to customize the way various features are presented to exhibit visitors.

5. Visit the Spotlight [documentation pages](https://github.com/sul-dlss/spotlight/wiki) to learn how to add and edit feature pages, about pages, custom browse categories, and more.
````

If the links are an implementation problem, I think the new text would still be worth using without links. If the only issue with the links is the potential for breaking if pages on the Admin side are moved around, it seems like having a test for each link would mitigate that.

**Comment by cbeer** [comment]
@ggeisler is it ok if that text does not show up on the home page edit screen?

**Comment by ggeisler** [comment]
Sure, I guess, but how will the curator delete it?

**Comment by cbeer** [comment]
I can think of two options:

a) the curator wouldn't ever see it on the edit page. As soon as they save their own content, there's no more getting started directions

b) we have a widget called "getting started directions" that only shows up on the home page and only when the home page is otherwise empty. 


(a) is probably a whole lot easier. We even had most of that logic in place before, but I don't know if it's too mysterious.

**Comment by ggeisler** [comment]
Okay, sure, option a seems fine to me.

**Comment by cbeer** [comment]
Thanks

**Comment by cbeer** [comment]
Hm. I wonder if we should add some placeholder text for blank feature + about pages too.  @ggeisler?

**Comment by cbeer** [comment]
And, I'd like to add a case where the user is not yet logged in, e.g.

```
In order to curate exhibit content, you need to <%= link_to t('spotlight.header_links.login'), main_app.new_user_session_path %>
```

**Comment by ggeisler** [comment]
:+1: 

I'll create another ticket for the feature and about pages.
