### ISSUE TITLE
Records with only a single tag look funny

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#866]
e.g. https://exhibits.stanford.edu/maps-of-africa/spotlight/default-exhibit/catalog/kk053qk9156

**Comment by ggeisler** [comment]
How about something like this:

![tags-display](https://cloud.githubusercontent.com/assets/101482/6451307/8ed79d36-c0e2-11e4-8876-8366aec2dcc2.png)
----
I had to move the tags from a `ul` to a `dl` to do this, but if that's feasible I think this is a more useful display.

**Comment by cbeer** [comment]
Blocked by https://github.com/projectblacklight/blacklight/pull/1135
