### ISSUE TITLE
Update widget configuration panels - text and styling

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#871]
When recreating the maps of africa exhibit, I kept expecting the "display text on" to be "display image on" and regularly selected the wrong option.

**Comment by ggeisler** [comment]
Okay, sure. Let's change the label in the widget configuration to be "Display image on" and update the associated logic to arrange things correctly.

**Comment by cbeer** [comment]
The option grouping in #1011 may make this better.
