### ISSUE TITLE
Item + text widget should have more vertical padding around the image?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#872]
Right now it has none.

**Comment by ggeisler** [comment]
Maybe I don't have the right combination of widgets to see what you saw, but I don't see a need for any vertical padding. In the couple of examples below, I used a few different widget combinations and there seems to be adequate vertical padding for the Item + Text widget (at least as a default).

However, the Item + Text widget has a problem with horizontal alignment. See #985.

#### Example 1

![feature_page_one___default_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6468853/f59dbd7a-c18c-11e4-975e-26b15f86487a.png)

#### Example 2

![feature_page_two___default_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6468866/12cae8e6-c18d-11e4-9cfe-d508f6ce499a.png)

**Comment by jkeck** [comment]
@ggeisler I think #1001 addresses this.  Maybe you can conform before we close this out.

**Comment by ggeisler** [comment]
Yep.
