### ISSUE TITLE
Make Admin > Settings into tabbed pages with import/export added

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#886]
I wonder if we have an issue w/ the wording of some of the sidebar links.

There is an `Import/Export` link which I keep wanting to click to "import" things into the exhibit, however I actually "add/import" things using the `Items` link.  I understand it because I work on it internally but I wonder if we could do better about the wording for first-time users.

![import-confusion](https://cloud.githubusercontent.com/assets/96776/5824365/07d6dcfc-a099-11e4-9249-c673c46acafd.png)

Just a thought

**Comment by ggeisler** [comment]
This might now be less of an issue since only superadmins will see the `Import/Export` link?

But we could also change the name of the link to `Data import/export`, which I think would further help (still might not be completely unambiguous, but better).

**Comment by ggeisler** [comment]
![curation_-_dashboard___maps_of_africa__an_online_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6492728/760f4c52-c26a-11e4-9e02-1e81aad6a23f.png)

**Comment by ggeisler** [comment]
Here's a more involved but probably better solution, moving the import/export actions into tabs along with the settings and delete exhibit forms. I don't see any need for changes to the content of the tabbed pages; the work is just moving the existing content associated with each action into the tabs (though the import and export actions are not currently part of the settings page so I'm not sure if moving those to the settings page poses problems):

#### Remove the Import/export link from sidebar

![updated-sidebar](https://cloud.githubusercontent.com/assets/101482/6531965/f13ffb8c-c3f1-11e4-921f-536051b88fe5.png)
----

#### Settings - Basic settings tab

Current content of settings, but without the delete danger zone section:

![basic settings](https://cloud.githubusercontent.com/assets/101482/6531975/0fa96874-c3f2-11e4-9c5b-6e283cb072f6.png)
----

#### Settings - Import data tab

![import data](https://cloud.githubusercontent.com/assets/101482/6532009/52c1c91c-c3f2-11e4-9f87-a036a77b5b3c.png)
----

#### Settings - Export data tab

![export data](https://cloud.githubusercontent.com/assets/101482/6532017/604b7d08-c3f2-11e4-9e95-40e14543ce69.png)
----

#### Settings - Delete exhibit tab

![delete exhibit](https://cloud.githubusercontent.com/assets/101482/6532025/6a4abe86-c3f2-11e4-981a-77271763db05.png)
----

**Comment by cbeer** [comment]
:+1:
