### ISSUE TITLE
undefined method `apply_permissive_visibility_filter' for #<CatalogController:0x007f53045dc970>

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#896]
e.g.

```
GET https://exhibits.stanford.edu/maps-of-africa/catalog/citation?id=mj183kc2482
```

**Comment by jkeck** [comment]
Just from a quick look at squash I'm curious why this isn't being handled by the `Spotlight::CatalogController`.  I know we don't override the #citation, #sms, etc actions, but  we're sub-classing from `::CatalogController` so we should get them when going through ours (and I think using the app's controller directly will potentially cause problems).

**Comment by cbeer** [comment]
I'm still trying to track down how googlebot is getting to `/catalog` in the first place. I haven't found any links for it yet, and i was hoping webmaster tools might enlighten us, but no joy yet.

**Comment by cbeer** [comment]
Don't do this:

```
 self.solr_search_params_logic << :apply_permissive_visibility_filter
```
