### ISSUE TITLE
Labels for non-repository item upload form

### ISSUE THREAD

**Issue by snydman** [sul-dlss/spotlight#900]
Odd labeling seen below.

![image](https://cloud.githubusercontent.com/assets/3279382/5908261/c8bde288-a55a-11e4-9dbb-973a301a480f.png)

**Comment by jkeck** [comment]
I *think* this is/will be addressed by adding those fields to the app's Blacklight configuration (which we will generate for new apps being created).

In addition, it's also possible to add i18n strings for these fields (which is what this is falling back on using the i18n missing translation strategy) although that's probably not what we want to do.

**Comment by cbeer** [comment]
I hope so. I got 1/2 way through redeploying apps before getting distracted by a sitemap problem and the assets issue. Hopefully tomorrow we'll be able to resolve both.
