### ISSUE TITLE
how to add another sort widget

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#907]
I tried add add_sort2_field method in configuration_spec.rb 
and  add config.add_sort2_field 'type', sort: 'type asc', label: 'Type' in catalog_controller.rb
but it reports add_sort2_field method undefined, how should I define the methods in catalog_controller.rb?  Thanks!

**Comment by jkeck** [comment]
@whisere the method to add sort fields is `add_sort_field` not `add_sort2_field`.

https://github.com/projectblacklight/blacklight/wiki/Configuration---Solr-fields#sort-fields

**Comment by whisere** [comment]
Thanks! But if I need to add other widgets similar to the original sort widget on the page for a second sort, and widget to choose grouping etc, can I use other get field methods on the catalog_controller.rb? eg add_group_field and define the method in configuration_spec.rb ?

**Comment by jkeck** [comment]
Closing as I believe this has been taken to the Blacklight-development list.

**Comment by whisere** [comment]
I accidentally posted it to the blacklight google list, but can't find it after I posted, can you please add the post link here if you see it? Thanks!

**Comment by jkeck** [comment]
The Blacklight list is the correct place for this type of question: https://groups.google.com/forum/#!searchin/blacklight-development/Junran/blacklight-development/dymt_9B_NJs/RPFUANtWOT4J
