### ISSUE TITLE
New widget: Feature feature pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#915]

**Comment by ggeisler** [comment]
@cbeer has already started work on this in #974, but in case it helps here is the design idea I was working on for this (based on a discussion with @jkeck who suggested the potential of using tabs on the feature page in edit mode). 

This is to enable the curator to select and crop an image to serve as the representative image for a feature page, with the feature page widget in mind. Whether this is sufficient for a new way of presenting feature pages themselves is unclear until we have a final plan for the exhibity look of feature pages.

Since each feature page needs its own image, the most obvious place for the curator to select the image is in edit mode when working on the page (we don't currently have a focused edit page for a feature page on the dashboard side, as we do with the browse categories). If we can modify the current Page Options box on the feature page to a tabbed view, we can nicely separate the page content, page options, and page thumbnail as separate things for the curator to work on. Something like this:

#### Content tab
![feature-page-content-tab](https://cloud.githubusercontent.com/assets/101482/6432467/f4c1f23a-c007-11e4-9252-f20586671383.png)

----
#### Options tab
![feature-page-options-tab](https://cloud.githubusercontent.com/assets/101482/6432469/008204fc-c008-11e4-9d1e-42ebf78cbc0f.png)

----
#### Thumbnail tab
![feature-page-thumbnail-tab](https://cloud.githubusercontent.com/assets/101482/6432461/9be3edbc-c007-11e4-9faa-ad50685636ca.png)
----
As shown above, this page could be very similar to the image selection and cropping setup for the site masthead, except we can fix the crop box dimensions to 400px by 300px.

The alternative to the approach above is to rethink how feature pages are presented on the dashboard side, so that we have a separate edit page there (similar to how each browse category has its own edit page) where the curator can select the thumbnail. But the approach above seems preferable to me, if it is feasible.

**Comment by cbeer** [comment]
Fixed by #1011
