### ISSUE TITLE
Exhibity-style browse detail page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#919]
Related to #786

**Comment by ggeisler** [comment]
For the display side of this, when the curator selects the "Show browse category masthead" option in the Browse Category Edit page, we need to update the masthead and menu bar area of that browse category detail to be something like below.

- Hide search box
- Move menu nav to right-alignment
- Put site title and menu nav in same section
- Show the selected browse category masthead image, with title and item count

![3 browse-detail-collapsed-masthead](https://cloud.githubusercontent.com/assets/101482/6492592/b4450e0e-c269-11e4-9cbf-fd1fb6ce6077.png)

**Comment by jkeck** [comment]
@ggeisler just to confirm since it's not in the mockup but you didn't explicitly mention removing it.

When we're displaying the search specific masthead, should we remove the breadcrumb?

**Comment by ggeisler** [comment]
Yeah, my thought was for any page in "exhibity" mode or "museum style" we would hide the breadcrumbs. It's a little fuzzier now because we're making some things default that I previously was thinking would be only shown if "museum style" was selected, so I worry about inconsistency, but let's try it with the breadcrumbs hidden.
