### ISSUE TITLE
config.add_index_field and config.add_show_field

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#923]
As I understand config.add_show_field is the fields showing in record page (eg http://localhost:3000/spotlight/default-exhibit/catalog/2106056657), while config.add_index_field is the fields showing in search page (http://localhost:3000/spotlight/default-exhibit/catalog?f%5Bformat%5D%5B%5D=Book), but I am having problem with record page fields, they are showing the fields in add_index_field instead of those in add_show_field. How can I set the fields in record different from the fields in search page? Thanks!

**Comment by jkeck** [comment]
I believe the thinking here is that you can configure ALL possible fields in you application level config (most likely in your `CatalogController`) which will then make all those fields present in your administration interface (`/spotlight/:exhibit_slug/edit/metadata`).  Then the fields that show in the different views (Item Details, List, Gallery, etc) can be configured in that interface on an exhibit-by-exhibit basis.

Why the configured index fields are the ones that we use explicitly to drive the default configuration is something I don't know off the top of my head, but I'm sure there's a reason behind it.

I believe this is something that we should be doing a better job of documenting (which we plan on spending some time in February to work on updating).

**Comment by whisere** [comment]
Thanks very much! configuration in default-exhibit/edit/metadata works perfectly.
