### ISSUE TITLE
bookmark problem

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#926]
when I open the bookmark page 
shows error below:

NoMethodError in BookmarksController#index
undefined method `apply_permissive_visibility_filter' for #<BookmarksController:0xcc1a5b4>
Extracted source (around line #51):

Blacklight::Solr::Request.new.tap do |solr_parameters|
solr_search_params_logic.each do |method_name|
send(method_name, solr_parameters, user_params)
end
end
end

Rails.root: spotlight/spec/internal
Application Trace | Framework Trace | Full Trace

blacklight (5.8.2) lib/blacklight/request_builders.rb:51:in `block (2 levels) in solr_search_params'
blacklight (5.8.2) lib/blacklight/request_builders.rb:50:in `each'
blacklight (5.8.2) lib/blacklight/request_builders.rb:50:in `block in solr_search_params'
blacklight (5.8.2) lib/blacklight/request_builders.rb:49:in `tap'
blacklight (5.8.2) lib/blacklight/request_builders.rb:49:in `solr_search_params'
blacklight (5.8.2) lib/blacklight/solr_helper.rb:98:in `query_solr'
blacklight (5.8.2) lib/blacklight/solr_helper.rb:140:in `get_solr_response_for_document_ids'
blacklight (5.8.2) lib/blacklight/bookmarks.rb:42:in `index'
......

Any idea? Thanks!

**Comment by cbeer** [comment]
This should be fixed by #906
