### ISSUE TITLE
when facet.missing=true

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#932]
When facet field set as  <str name="facet.missing">true</str> in solr
The facet item shows as url instead of 'missing' on the facet bar 
eg: 
Event                                                                 100
http://localhost:3000/spotlight/default-exhibit/catalog?exhibit_id=default-exhibit&f%5Blocation%5D%5B%5D=&only_path=true                                         8

**Comment by cbeer** [comment]
It looks like blacklight does not support facet.missing. Could you file a bug there?
