### ISSUE TITLE
Create spotlight.projectblacklight.org

### ISSUE THREAD

**Issue by snydman** [sul-dlss/spotlight#938]
We need a polished project site, for documentation and marketing.  This should not be Stanford hosted.

Something off projectblacklight.org is an option, but that site is so dated at this point and we don't yet have community consensus on where such sub-sites would go.

I'd propose for our short-to-medium term goals we set up spotlight.github.io, which seems available. 

This one for you @ggeisler ?

**Comment by ggeisler** [comment]
Yep, I like the spotlight.github.io option. Will get something started soon.

**Comment by cbeer** [comment]
Well, it can't be `spotlight.github.io` because we don't own that account. sul-dlss.github.io/spotlight or doing a CNAME (spotlight.projectblacklight.org or whatever) are options.

**Comment by snydman** [comment]
I kindof like the spotlight.projectblacklight.org CNAME option.

**Comment by cbeer** [comment]
I believe @bess has the power to set that up.

**Comment by cbeer** [comment]
@bess set up the CNAME this morning and I populated https://github.com/sul-dlss/spotlight/tree/gh-pages with a stub page: http://spotlight.projectblacklight.org/

**Comment by snydman** [comment]
:+1:
