### ISSUE TITLE
Put Appearance page sections into tabs

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#941]
The Administration > Appearance page contains several distinct configuration areas, plus we're going to need a new one for selecting and cropping the site masthead image. To make working with these configurations easier, I suggest we reorganize these sections into a tabbed interface (in case it's relevant, note that we might to do this other Admin/Curator pages eventually):

![administration_-_appearance___maps_of_africa__an_online_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6259341/91169864-b786-11e4-884b-c01474f3c82c.png)

Here's how each tabbed section might look (Site masthead details will part of a new ticket):

![tabs](https://cloud.githubusercontent.com/assets/101482/6259386/e86b41b4-b786-11e4-9730-975f61cc8ca6.gif)

**Comment by cbeer** [comment]
I wonder if sort fields should get its own page. I suspect it's only on this page for convenience.

**Comment by ggeisler** [comment]
True, it’s not much different than the Facet configuration page. We could move it to its own page under Curation > Facets in the sidebar.
