### ISSUE TITLE
Document Google Analytics Integration

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#949]
- [ ] Assumed Pre-requisite Google Analytics Setup
- [ ] How to tell spotlight where the .p12 file is located

**Comment by cbeer** [comment]
a) A [service account](https://developers.google.com/accounts/docs/OAuth2#serviceaccount) with [Google analytics API access](https://github.com/tpitale/legato/wiki/OAuth2-and-Google#registering-for-api-access) that has access to the Google Analytics web property (the service account's email client id needs to be registered with Google Analytics.. and it's an annoying, undocumented pain as far as I can tell)

b) Left as an exercise for the reader. You could do something like this in an initializer:

```
Spotlight::Analytics::Ga.pkcs12_key_path = Settings.ga.pkcs12_key_path
Spotlight::Analytics::Ga.email = Settings.ga.email
Spotlight::Analytics::Ga.web_property_id = Settings.ga.web_property_id
```

**Comment by cbeer** [comment]
Actually, maybe there's some benefit to turning it into `Spotlight::Engine.config` configuration too.
