### ISSUE TITLE
Add Engine configuration to optionally add Google Analytics tracking code?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#951]
We could do something as simple as auto-generate the Google Analytics code into the layout when an implementor has configured a tracking code or integrate w/ something more involved.

Just a thought on something that could allow the Google Analytics integration to be a bit easier.

**Comment by cbeer** [comment]
Might as well, I suppose. I'll do it in a nice, separate partial in case people need to override it.
