### ISSUE TITLE
Only selecting one view type does not set that view as default

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#959]
Example Config:
![screen shot 2015-02-20 at 6 05 00 pm](https://cloud.githubusercontent.com/assets/96776/6312383/2f7ba7b0-b92b-11e4-8555-2621a6be8a94.png)

Now when going to a result set w/o a `view` param the default view is list and not the configured view.  FWIW, if I add `&view=masonry` (or ANY view type) to the URL and then remove it the default view type appears to remain "sticky" to whatever the last view my session used.

![screen shot 2015-02-20 at 6 06 07 pm](https://cloud.githubusercontent.com/assets/96776/6312400/d86a796e-b92b-11e4-91ac-9f9620e46bce.png)

**Comment by cbeer** [comment]
Is it possible `list` was sticky in the first place? Seems like it might be a problem with https://github.com/projectblacklight/blacklight/pull/982/files#diff-cde7e888634c89460ec31a49f24bdc20R187

**Comment by jkeck** [comment]
Yup, that looks like the culprit.  It's sticky to whatever the last view present in the session was in absence of a current view param.

**Comment by jkeck** [comment]
The issue here being there is now no way for that person to change the view to the type they're supposed to be viewing (which will most likely be the curators as their building their sites).
