### ISSUE TITLE
Add "Hide/Display" checkboxes to Main Menu admin

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#986]
This way an admin could decide to never show a "Browse" menu option but can create published browse categories to add to home, feature, and about pages.

**Comment by ggeisler** [comment]
Checkboxes checked by default.

Updated text is kind of wordy but let's go with this for now and I might update when doing some styling updates in the future:

>
Select the menu items you want to be displayed in the main navigation menu (menu items are only displayed when published pages exist for that item). Click a menu item to change its display label. Drag and drop a menu item to change their order in the menu.


![administration_-_appearance___maps_of_africa__an_online_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6493950/3c08be36-c273-11e4-85c7-1a8c8e318b55.png)
